# Generated by Django 3.2.10 on 2021-12-28 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_emails", "0002_auto_20211228_1949"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="templatevariable",
            name="email",
        ),
        migrations.DeleteModel(
            name="Email",
        ),
        migrations.DeleteModel(
            name="TemplateVariable",
        ),
    ]
